IF OBJECT_ID('dbo.cic_typed', 'U') IS NOT NULL
    DROP TABLE dbo.cic_typed;
GO

UPDATE raw_flows
SET source_day = 'Thursday-Afternoon'
WHERE source_file = 'thursday-workinghours-afternoon-infileteration.pcap_iscx.csv';
GO

SELECT
    TRY_CAST(source_port AS INT)                       AS source_port,
    TRY_CAST(destination_port AS INT)                  AS destination_port,
    protocol,
    TRY_CONVERT(DATETIME, [timestamp], 103)             AS [timestamp],
    TRY_CAST(flow_duration AS FLOAT)                    AS flow_duration,
    TRY_CAST(total_fwd_packets AS FLOAT)                AS total_fwd_packets,
    TRY_CAST(total_backward_packets AS FLOAT)           AS total_backward_packets,
    TRY_CAST(total_length_of_fwd_packets AS FLOAT)      AS total_length_of_fwd_packets,
    TRY_CAST(total_length_of_bwd_packets AS FLOAT)      AS total_length_of_bwd_packets,
    TRY_CAST(fwd_packet_length_max AS FLOAT)            AS fwd_packet_length_max,
    TRY_CAST(fwd_packet_length_min AS FLOAT)            AS fwd_packet_length_min,
    TRY_CAST(fwd_packet_length_mean AS FLOAT)           AS fwd_packet_length_mean,
    TRY_CAST(fwd_packet_length_std AS FLOAT)            AS fwd_packet_length_std,
    TRY_CAST(bwd_packet_length_max AS FLOAT)            AS bwd_packet_length_max,
    TRY_CAST(bwd_packet_length_min AS FLOAT)            AS bwd_packet_length_min,
    TRY_CAST(bwd_packet_length_mean AS FLOAT)           AS bwd_packet_length_mean,
    TRY_CAST(bwd_packet_length_std AS FLOAT)            AS bwd_packet_length_std,
    TRY_CAST(flow_bytes_s AS FLOAT)                     AS flow_bytes_s,
    TRY_CAST(flow_packets_s AS FLOAT)                   AS flow_packets_s,
    TRY_CAST(flow_iat_mean AS FLOAT)                    AS flow_iat_mean,
    TRY_CAST(flow_iat_std AS FLOAT)                     AS flow_iat_std,
    TRY_CAST(flow_iat_max AS FLOAT)                     AS flow_iat_max,
    TRY_CAST(flow_iat_min AS FLOAT)                     AS flow_iat_min,
    TRY_CAST(fwd_iat_total AS FLOAT)                     AS fwd_iat_total,
    TRY_CAST(fwd_iat_mean AS FLOAT)                      AS fwd_iat_mean,
    TRY_CAST(fwd_iat_std AS FLOAT)                       AS fwd_iat_std,
    TRY_CAST(fwd_iat_max AS FLOAT)                       AS fwd_iat_max,
    TRY_CAST(fwd_iat_min AS FLOAT)                       AS fwd_iat_min,
    TRY_CAST(bwd_iat_total AS FLOAT)                     AS bwd_iat_total,
    TRY_CAST(bwd_iat_mean AS FLOAT)                      AS bwd_iat_mean,
    TRY_CAST(bwd_iat_std AS FLOAT)                       AS bwd_iat_std,
    TRY_CAST(bwd_iat_max AS FLOAT)                       AS bwd_iat_max,
    TRY_CAST(bwd_iat_min AS FLOAT)                       AS bwd_iat_min,
    TRY_CAST(fwd_psh_flags AS FLOAT)                     AS fwd_psh_flags,
    TRY_CAST(bwd_psh_flags AS FLOAT)                     AS bwd_psh_flags,
    TRY_CAST(fwd_urg_flags AS FLOAT)                     AS fwd_urg_flags,
    TRY_CAST(bwd_urg_flags AS FLOAT)                     AS bwd_urg_flags,
    TRY_CAST(fwd_header_length AS FLOAT)                 AS fwd_header_length,
    TRY_CAST(bwd_header_length AS FLOAT)                 AS bwd_header_length,
    TRY_CAST(fwd_packets_s AS FLOAT)                     AS fwd_packets_s,
    TRY_CAST(bwd_packets_s AS FLOAT)                     AS bwd_packets_s,
    TRY_CAST(min_packet_length AS FLOAT)                 AS min_packet_length,
    TRY_CAST(max_packet_length AS FLOAT)                 AS max_packet_length,
    TRY_CAST(packet_length_mean AS FLOAT)                AS packet_length_mean,
    TRY_CAST(packet_length_std AS FLOAT)                 AS packet_length_std,
    TRY_CAST(packet_length_variance AS FLOAT)            AS packet_length_variance,
    TRY_CAST(fin_flag_count AS FLOAT)                    AS fin_flag_count,
    TRY_CAST(syn_flag_count AS FLOAT)                    AS syn_flag_count,
    TRY_CAST(rst_flag_count AS FLOAT)                    AS rst_flag_count,
    TRY_CAST(psh_flag_count AS FLOAT)                    AS psh_flag_count,
    TRY_CAST(ack_flag_count AS FLOAT)                    AS ack_flag_count,
    TRY_CAST(urg_flag_count AS FLOAT)                    AS urg_flag_count,
    TRY_CAST(cwe_flag_count AS FLOAT)                    AS cwe_flag_count,
    TRY_CAST(ece_flag_count AS FLOAT)                    AS ece_flag_count,
    TRY_CAST(down_up_ratio AS FLOAT)                     AS down_up_ratio,
    TRY_CAST(average_packet_size AS FLOAT)               AS average_packet_size,
    TRY_CAST(avg_fwd_segment_size AS FLOAT)              AS avg_fwd_segment_size,
    TRY_CAST(avg_bwd_segment_size AS FLOAT)              AS avg_bwd_segment_size,
    TRY_CAST(fwd_avg_bytes_bulk AS FLOAT)                AS fwd_avg_bytes_bulk,
    TRY_CAST(fwd_avg_packets_bulk AS FLOAT)              AS fwd_avg_packets_bulk,
    TRY_CAST(fwd_avg_bulk_rate AS FLOAT)                 AS fwd_avg_bulk_rate,
    TRY_CAST(bwd_avg_bytes_bulk AS FLOAT)                AS bwd_avg_bytes_bulk,
    TRY_CAST(bwd_avg_packets_bulk AS FLOAT)              AS bwd_avg_packets_bulk,
    TRY_CAST(bwd_avg_bulk_rate AS FLOAT)                 AS bwd_avg_bulk_rate,
    TRY_CAST(subflow_fwd_packets AS FLOAT)               AS subflow_fwd_packets,
    TRY_CAST(subflow_fwd_bytes AS FLOAT)                 AS subflow_fwd_bytes,
    TRY_CAST(subflow_bwd_packets AS FLOAT)               AS subflow_bwd_packets,
    TRY_CAST(subflow_bwd_bytes AS FLOAT)                 AS subflow_bwd_bytes,
    TRY_CAST(init_win_bytes_forward AS FLOAT)            AS init_win_bytes_forward,
    TRY_CAST(init_win_bytes_backward AS FLOAT)           AS init_win_bytes_backward,
    TRY_CAST(act_data_pkt_fwd AS FLOAT)                  AS act_data_pkt_fwd,
    TRY_CAST(min_seg_size_forward AS FLOAT)              AS min_seg_size_forward,
    TRY_CAST(active_mean AS FLOAT)                       AS active_mean,
    TRY_CAST(active_std AS FLOAT)                        AS active_std,
    TRY_CAST(active_max AS FLOAT)                        AS active_max,
    TRY_CAST(active_min AS FLOAT)                        AS active_min,
    TRY_CAST(idle_mean AS FLOAT)                         AS idle_mean,
    TRY_CAST(idle_std AS FLOAT)                          AS idle_std,
    TRY_CAST(idle_max AS FLOAT)                          AS idle_max,
    TRY_CAST(idle_min AS FLOAT)                          AS idle_min,
    LTRIM(RTRIM(label))                                  AS label,
    source_day
INTO cic_typed
FROM raw_flows;